name: 'shlokas-tests'
version: "3"

services:
  e2e:
    build: .
    environment:
      - CI=1
      - WORKERS=2
      - SHLOKAS_URL=http://shlokas
      - MAIL_URL=http://mail:1080
    volumes:
      - ./report:/e2e/report
    networks:
      - shlokas


networks:
  shlokas:
    name: shlokas
