name: shlokas
version: '3'

services:
  e2e:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USER_UID=${UID:-1003}
        - USER_GID=${UID:-1003}
    expose:
      - 8080
    networks:
      - shlokas
    volumes:
      - ..:/workspaces

networks:
  shlokas:
    name: shlokas
